
########################################################################
# Definitions common to all Makefiles (library and firmware)
# Include Makefile.<compiler>_defs first to define CC

MCC         ?= sdcc
RM          ?= rm 
LIB         = OpenVex.lib
DEBUG       ?= 1
SED         ?= sed

MAKEFILE_DEPEND = Makefile.depend.${MCC}

